[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = [
    "qemu-system-aarch64",
    "-M", "virt",
    "-cpu", "max",
    "-nographic",
    "-device", "virtio-net-device,netdev=net0",
    "-netdev", "user,id=net0",
    "-device", "virtio-rng-device",
    "-kernel"
]

rustflags = [
    "-C", "link-arg=-Tlink.ld"
]