[target.aarch64-unknown-none]
runner = [
    "qemu-system-aarch64",
    "-M", "virt",
    "-cpu", "max",
    "-m", "128M",
    "-nographic",
    "-global", "virtio-mmio.force-legacy=false",
    "-device", "virtio-net-device,netdev=net0,mac=52:54:00:12:34:56",
    "-netdev", "tap,id=net0,ifname=tap0,script=no,downscript=no",
    "-device", "virtio-rng-device",
    "-kernel"
]

rustflags = [
    "-C", "link-arg=-Tlink.ld"
]