FROM rust:latest AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    libssl-dev \
    ca-certificates \
    curl \
    git \
    lld \
    gcc-aarch64-linux-gnu \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/multikeyauthiot

COPY . .

ARG KEYS
ARG SKEY
ARG KEY_COUNT
ARG IOT_UID
ARG P

ENV KEYS=$KEYS \
    SKEY=$SKEY \
    KEY_COUNT=$KEY_COUNT \
    IOT_UID=$IOT_UID \
    P=$P

RUN rustup target add aarch64-unknown-none && \
    cd iot_device && \
    cargo build --release --target aarch64-unknown-none

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    qemu-system-arm \
    qemu-system-aarch64 \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/multikeyauthiot/iot_device/target/aarch64-unknown-none/release/iot_device /usr/local/bin/iot_device

ENV KEYS="" \
    SKEY=""

ENTRYPOINT ["qemu-system-aarch64", \
    "-M", "virt", \
    "-cpu", "cortex-a72", \
    "-m", "128M", \
    "-nographic", \
    "-global", "virtio-mmio.force-legacy=false", \
    "-device", "virtio-net-device,netdev=net0", \
    "-netdev", "user,id=net0", \
    "-device", "virtio-rng-device", \
    "-kernel", "/usr/local/bin/iot_device"]
CMD []