services:
  tls-init:
    image: alpine/openssl
    volumes:
      - ./tls:/tls
    entrypoint: sh
    command: >
      -c "openssl req -x509 -newkey rsa:2048 -nodes
      -keyout /tls/vault-key.pem -out /tls/vault-cert.pem
      -days 1 -subj '/CN=vault'
      -addext 'subjectAltName=DNS:vault,DNS:localhost,IP:127.0.0.1'"

  vault:
    image: hashicorp/vault
    restart: "no"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl
      - ./tls:/vault/tls
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_SKIP_VERIFY=true
    ports:
      - "8200:8200"
    entrypoint: ["vault"]
    command: ["server", "-config=/vault/config/vault-config.hcl"]
    depends_on:
      tls-init:
        condition: service_completed_successfully
    
  vault-init:
    build: ./vault-init
    depends_on:
      - vault
    volumes:
      - ./tls:/tls
      - ./vault-init-out:/out
    entrypoint: sh
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_CACERT: /tls/vault-cert.pem
    command:
      - -c
      - |
        set -x
        until vault status >/dev/null 2>&1; [ $$? -ne 1 ]; do sleep 1; done

        vault operator init -key-shares=1 -key-threshold=1 -format=json > /out/init.json

        UNSEAL_KEY=$$(jq -r '.unseal_keys_b64[0]' /out/init.json)
        ROOT_TOKEN=$$(jq -r '.root_token' /out/init.json)

        vault operator unseal "$$UNSEAL_KEY"
        export VAULT_TOKEN="$$ROOT_TOKEN"

        printf 'path "secret/data/iot_device/*" {\n  capabilities = ["create", "read", "update"]\n}\n' > /tmp/iot-device-policy.hcl

        vault policy write iot-device-policy /tmp/iot-device-policy.hcl
        vault token create -policy=iot-device-policy -field=token > /out/service-token.txt

  server:
    build: ./server
    depends_on:
      - vault-init
    volumes:
      - ./vault-init-out:/vault-init-out
      - ./tls:/tls
    env_file:
      - .env
    networks:
      iot_net:
        ipv4_address: 172.20.0.2
    ports: 
      - "5683:5683/udp"
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_CACERT: /tls/vault-cert.pem
      IOT_UIDS: "1"
      SERVER_KEYS: ${SERVER_KEYS:-}
      SERVER_P: ${P:-3}

  iot_device: 
    build:
      context: ./iot_device
      dockerfile: dockerfile
      args:
        KEYS: ${KEYS:-}
        SKEY: ${SKEY:-}
        KEY_COUNT: ${KEY_COUNT:-16}
        IOT_UID: ${IOT_UID:-1}
        P: ${P:-3}
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - server
    networks:
      iot_net:
        ipv4_address: 172.20.0.3
    environment:
      - SERVER_IP=172.20.0.2
      - SERVER_PORT=5683
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      
networks:
  iot_net:
    ipam:
      config: 
        - subnet: 172.20.0.0/16